services:
    php:
        container_name: my_php
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www/html
            # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        ports:
            - 9000:9000
            - 3000:3000
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            XDEBUG_CONFIG: 
                client_host=host.docker.internal 
                client_port=9003
        user: "1000:1000"
        networks:
            - my_network
    nginx:
        image: nginx:1.13.8
        container_name: my_nginx
        ports:
            - 8000:80
        volumes:
            - ./www:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
        depends_on:
            - php
        networks:
            - my_network
 
    mysql:
        image: mysql
        container_name: my_mysql
        env_file:
        - ".env"
        volumes:
            - ./data/db:/var/lib/mysql
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - my_network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my_phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    mailhog:
        image: mailhog/mailhog
        container_name: my_mailhog
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MH_STORAGE: memory
        depends_on:
            - php
        networks:
            - my_network
networks:
    my_network:
        driver: bridge
